services:
  app:
    container_name: place-marker-app
    build:
      dockerfile: Dockerfile.dev
      context: ./
    environment:
      CLIENT_ID: ${CLIENT_ID}
    restart: on-failure

  nginx:
    container_name: place-marker-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - app
    depends_on:
      - app
    restart: always
